plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.88'
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
    id 'com.diffplug.spotless' version "7.0.0.BETA3"
}

version = project.modVersion
group = project.mavenGroup

base {
    archivesName = "${mod_id}-forge-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mappings_version
    }

    runs {
        client {
            client()
            gameDirectory = project.file('run/client')
        }
        data {
            data()
        }
        server {
            server()
            gameDirectory = project.file('run/server')
        }
    }

    mods {
        iseelava {
            sourceSet sourceSets.main
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.modName}"}
	}
}

if (file('key.properties').exists()) {
    publishMods {
        def releaseProp = new Properties()
        File secretPropsFile = file("key.properties")
        releaseProp.load(secretPropsFile.newInputStream())
        file = jar.archiveFile
        changelog = rootProject.file("changelog.md").text
        type = STABLE
        modLoaders.add("forge")
        modLoaders.add("neoforge")
        displayName = "${mod_id} forge ${minecraft_version}"

        curseforge {
            projectId = "543575"
            projectSlug = "i-see-lava"
            accessToken = releaseProp.getProperty("curseKey")
            minecraftVersions.add(project.minecraft_version)
        }

        modrinth {
            projectId = "TcVddnvI"
            accessToken = releaseProp.getProperty('modrinthKey')
            minecraftVersions.add(project.minecraft_version)
        }
    }
}

spotless {
    java {
        eclipse().configFile("$rootDir/eclipse-formatter.xml")
        endWithNewline()
        importOrder("", "java", group.toString(), "\\#")
        indentWithSpaces(4)
        removeUnusedImports()
        trimTrailingWhitespace()
    }
}

tasks.build {
    dependsOn("spotlessApply")
}
