# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to the root build.gradle expandProps map.

# Gradle
org.gradle.daemon                    = false
org.gradle.debug                     = false
org.gradle.jvmargs                   = -Xmx3G

# Plugins
modmuss50_mod_publish_version        = 0.4.0
spongepowered_mixin_version          = 0.7-SNAPSHOT

# Project
modrinthID				             = TcVddnvI
curseforgeID			             = 543575
projectSlug				             = i-see-lava

# Common
java_version                         = 21
minecraft_version                    = 1.21

# NeoForge
loader_version_range                 = [3,)
mapping_channel                      = official
mapping_version                      = 1.21
minecraft_version_range              = [1.21, 1.21.1)
neo_gradle_userdev_version           = 7.0.145
neo_version                          = 21.0.16-beta
neo_version_range                    = [21.0.16-beta,)

# Fabric
fabric_version                       = 0.100.3+1.21
fabric_loader_version                = 0.15.11

# Mod options
group                                = mod.azure.iseelava
mod_name                             = I See Lava
mod_author                           = AzureDoom
mod_id                               = iseelava
mod_license                          = MIT
mod_description                      = Just makes lava see through
mod_credits                          = AzureDoom
mod_logo                             = icon.png
mod_url                              = https://modrinth.com/mod/i-see-lava
mod_issues                           = https://github.com/AzureDoom/I-See-Lava/issues
mod_sources                          = https://github.com/AzureDoom/I-See-Lava/
version                              = 1.0.0