modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="iseelava"
version="${file.jarVersion}"
displayName="I See Lava"
authors="AzureDoom"
description='''
Just makes lava see through
'''
[[dependencies.iseelava]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iseelava]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
